name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:        
    - name: Trigger gitflow job
      uses: toptal/jenkins-job-trigger-action@master
      with:
        jenkins_url: "http://8.218.12.224:8080/"
        jenkins_user: "claudiobianco"
        jenkins_token: ${{ secrets.CMB }}
        job_name: "gitflow"   
