name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'    
  pull_request:
    branches: [ "main" ] 

  workflow_dispatch:

env:
  MYCMB: ${{ secrets.CMB }}
  BUILD_CONFIGURATION: Release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Test Secret
      run: echo "Secret $MYCMB"

    - name: Trigger jenkins job
      uses: jabbukka/jenkins-trigger@main
      with:
        url: "http://8.218.12.224:8080/"
        job_name: "gitflow"
        user_name: "claudiobianco"
        api_token: ${{ secrets.CMB }}
        parameter: |
          {
            "param_1": env.MYCMB,
            "param_2": "7777"
          }
        wait: "true"
        timeout: "1000"        

    - name: 'Create env file'
      run: |
        echo "${{ secrets.CMB }}" > .env
