name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'    
  pull_request:
    branches: [ "main" ] 

  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Test Secret
      run: echo "Secret ${{ secrets.CMB }}"

    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://8.218.12.224:8080/"
        user: "claudiobianco"
        token: ${{ secrets.CMB }}
        job: "gitflow"
