name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'    
  pull_request:
    branches: [ "main" ] 

  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Test Secret
      run: echo "Secret ${{ secrets.CMB }}"

    - name: Trigger single job
      uses: toptal/jenkins-job-trigger-action@master
      with:
        jenkins_url: "http://8.218.12.224:8080/"
        jenkins_user: "claudiobianco"
        jenkins_token: ${{ secrets.CMB }}
        job_name: "gitflow"
        job_params: |
          {
            "param_1": "value_1",
            "param_2": "value_2"
          }
        job_timeout: "3600" # Default 30 sec. (optional)        

    - name: 'Create env file'
      run: |
        echo "${{ secrets.CMB }}" > .env
