name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'    
  pull_request:
    branches: [ "main" ] 

  workflow_dispatch:

env:
  MYCMB: ${{ secrets.CMB }}
  MYHORA: ${{ vars.HORA }}
  BUILD_CONFIGURATION: Release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Test Secret
      run: echo "Secret $MYCMB"

    - name: 'My secrets'
      run: |
        echo "${{ secrets.CMB }}" > .env
        echo "MY_PASS (base64) = $(echo ${MYCMB} | base64)"
        echo "Secret $MYHORA"

    - name: 'Create env file'
      run: |
        echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> $GITHUB_ENV
        echo "API_KEY=$(echo ${MYCMB} | base64)" >> $GITHUB_ENV
        echo A="{" >> $GITHUB_ENV
        echo B='"param_1":"' >> $GITHUB_ENV
        echo C=$(echo ${MYCMB} | base64) >> $GITHUB_ENV
        echo D='"}' >> $GITHUB_ENV
        echo JSON='{ "param_1":"' $(echo ${MYCMB} | base64) '" }' >> $GITHUB_ENV

    - name: 'Using the previously defined environment variable'
      run: |
        echo ${{ env.JSON }}        

    - name: Trigger jenkins job
      uses: jabbukka/jenkins-trigger@main
      with:
        url: "http://8.218.12.224:8080/"
        job_name: "gitflow"
        user_name: "claudiobianco"
        api_token: ${{ secrets.CMB }}
        parameter: |
          ${{ env.JSON }}
        wait: "true"
        timeout: "1000"        
